"use client";

import { useMemo } from "react";
import { useParams, usePathname } from "next/navigation";
import { ShieldCheck, Info, FileText, Lock, Truck, RefreshCw, AlertCircle } from "lucide-react";
import { Card } from "@/components/ui/card";

const policiesData: Record<string, {
  title: string;
  subtitle: string;
  icon: any;
  intro: string;
  sections: { title: string; paragraphs: string[] }[];
}> = {
  "medical-disclaimer": {
    title: "Medical & Wellness Disclaimer",
    subtitle: "Understanding the Boundaries of Our Guidance",
    icon: ShieldCheck,
    intro: "Please read this medical and wellness notice carefully before engaging with Nirogi Tanman services.",
    sections: [
      {
        title: "1. Not Emergency Medical Services",
        paragraphs: [
          "Nirogi Tanman is a platform for preventive healthcare and holistic wellness support.",
          "We do not provide emergency diagnostics, acute treatment plans, or critical medical dispatching.",
          "If you are experiencing a medical emergency, please call your local hospital lines immediately."
        ]
      },
      {
        title: "2. Educational Nature of AI Tools",
        paragraphs: [
          "Suggestions, metrics, and profiles generated by our AI health assistants are for educational habits mapping.",
          "They do not replace board-certified physician diagnoses or active prescription plans.",
          "Always verify AI recommendations with your human care team before modifying schedules."
        ]
      },
      {
        title: "3. Professional Consultations",
        paragraphs: [
          "Prescriptions and clinical diagnoses are only rendered by verified human practitioners during booked consults.",
          "User reliance on educational articles or guides is at their own discretion and responsibility."
        ]
      }
    ]
  },
  "consultation-consent": {
    title: "Consultation Consent",
    subtitle: "Patient Agreement for Digital Care & Consultations",
    icon: FileText,
    intro: "This agreement outlines parameters for online video consults and data coordination.",
    sections: [
      {
        title: "1. Telehealth Framework",
        paragraphs: [
          "You consent to receive health counseling, therapy recommendations, and clinical reviews via digital video.",
          "Online consults may have mechanical limitations compared to physical palpation diagnostics."
        ]
      },
      {
        title: "2. Shared Health Records",
        paragraphs: [
          "To enable integrated care, you consent to sharing vital records between your MD and yoga trainers.",
          "You can revoke diagnostic sharing permissions inside your settings cabinet at any time."
        ]
      },
      {
        title: "3. Privacy & Compliance",
        paragraphs: [
          "All video consultation logs, prescriptions, and message histories are protected under secure HIPAA standard audits."
        ]
      }
    ]
  },
  "shipping-policy": {
    title: "Shipping Policy",
    subtitle: "Delivery Rules for Ayurvedic Supplements & Formulations",
    icon: Truck,
    intro: "Information on packaging, shipping regions, and delivery timelines for our store items.",
    sections: [
      {
        title: "1. Packaging Rhythms",
        paragraphs: [
          "Formulations are bottled, sealed, and dispatched within 24-48 hours of payment verification.",
          "We use climate-controlled packages to ensure herbal extracts remain pure and potent."
        ]
      },
      {
        title: "2. Shipping Timelines",
        paragraphs: [
          "Metro cities: Delivery takes 3 to 5 business days from the dispatch alert.",
          "Other regions: Delivery takes 5 to 8 business days depending on courier accessibility."
        ]
      },
      {
        title: "3. Delivery Partners",
        paragraphs: [
          "We partner with secure courier networks. Tracking details sync instantly to your patient orders panel."
        ]
      }
    ]
  },
  "refund-policy": {
    title: "Return & Refund Policy",
    subtitle: "Returns and Claims for Organic Formulations",
    icon: RefreshCw,
    intro: "Terms for returns, exchanges, and refund claims on our physical supplements.",
    sections: [
      {
        title: "1. Quality Verification",
        paragraphs: [
          "Due to organic purity guidelines, opened herb bottles or custom packages cannot be returned.",
          "Unopened products with seals fully intact can be returned within 7 days of package delivery."
        ]
      },
      {
        title: "2. Damaged Packages",
        paragraphs: [
          "If a bottle arrives broken or leaking, submit photo logs to support within 24 hours.",
          "We will ship a replacement package free of charge after quick verification."
        ]
      },
      {
        title: "3. Refund Processing",
        paragraphs: [
          "Approved refund claims are credited to your original payment gateway within 5 to 7 billing days."
        ]
      }
    ]
  },
  "cancellation-policy": {
    title: "Cancellation Policy",
    subtitle: "Appointment and Subscription Cancellations",
    icon: AlertCircle,
    intro: "Guidelines for rescheduling consults and canceling wellness plans.",
    sections: [
      {
        title: "1. Booking Reschedules",
        paragraphs: [
          "You can reschedule or cancel a doctor session up to 24 hours prior to the slot time.",
          "Cancellations made within 24 hours are subject to a 50% reservation hold fee."
        ]
      },
      {
        title: "2. Care Plan Cancellation",
        paragraphs: [
          "Subscriptions can be canceled at any time inside your patient billing settings.",
          "Active monthly plans remain accessible until the end of the current billing cycle."
        ]
      },
      {
        title: "3. Practitioner Cancellations",
        paragraphs: [
          "If a practitioner cancels due to emergencies, a full refund or instant slot booking options are provided."
        ]
      }
    ]
  },
  "product-disclaimer": {
    title: "Product Disclaimer",
    subtitle: "Purity Details and Organic Certifications",
    icon: Info,
    intro: "Crucial regulatory guidelines regarding organic supplements and herbal complexe usage.",
    sections: [
      {
        title: "1. Organic Variations",
        paragraphs: [
          "Our herbs are harvested in batches. Color, taste, or texture variations are natural and normal.",
          "These natural changes do not reduce the active organic concentration of the compound."
        ]
      },
      {
        title: "2. Endocrine & Illness Flags",
        paragraphs: [
          "If you are pregnant, nursing, taking thyroid medications, or have clinical conditions, verify dosage with your doctor.",
          "Discontinue usage immediately if you experience unexpected digestive changes or skin reactions."
        ]
      },
      {
        title: "3. FDA / AYUSH Boundaries",
        paragraphs: [
          "Our supplements support wellness habits and prevent imbalances. They do not claim to replace hospital diagnostics."
        ]
      }
    ]
  }
};

const PolicyDetailPage = ({ forceSlug }: { forceSlug?: string }) => {
  const params = useParams();
  const pathname = usePathname();

  const activeSlug = useMemo(() => {
    if (forceSlug) return forceSlug;
    const pathParts = pathname.split("/");
    const lastPart = pathParts[pathParts.length - 1];
    return policiesData[lastPart] ? lastPart : "medical-disclaimer";
  }, [forceSlug, pathname]);

  const policy = useMemo(() => {
    return policiesData[activeSlug] ?? policiesData["medical-disclaimer"];
  }, [activeSlug]);

  const IconComponent = policy.icon;

  return (
    <div className="font-['Manrope',sans-serif] bg-[#FAF8F5] text-foreground min-h-screen pb-20 overflow-hidden">
      {/* Hero Banner with Background Gradient */}
      <section className="relative py-16 md:py-20 border-b border-border bg-hero-gradient">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,hsl(var(--primary)/0.03),transparent_55%)] pointer-events-none" />
        <div className="container mx-auto px-6 max-w-6xl relative z-10 space-y-4">
          <div className="flex items-center gap-2 text-primary font-extrabold text-xs uppercase tracking-widest">
            <IconComponent className="h-4 w-4" />
            <span>Legal Policy</span>
          </div>
          <h1 className="text-3xl sm:text-5xl font-extrabold text-foreground tracking-tight">{policy.title}</h1>
          <p className="text-muted-foreground text-sm font-light leading-relaxed max-w-2xl">
            {policy.subtitle}
          </p>
        </div>
      </section>

      {/* Main Content Split Layout */}
      <section className="py-12 md:py-16 container mx-auto px-6 max-w-6xl">
        <div className="grid gap-12 lg:grid-cols-[1.1fr_0.9fr] items-start">
          {/* Left Column: Detailed Policy Sections */}
          <div className="space-y-8">
            <Card className="surface-panel p-5 bg-white border border-border/80 rounded-2xl">
              <p className="text-xs text-primary font-semibold leading-relaxed">{policy.intro}</p>
            </Card>

            <div className="space-y-8">
              {policy.sections.map((sec, idx) => (
                <div key={idx} className="space-y-2 border-b border-border/40 pb-6">
                  <h3 className="text-base font-bold text-foreground">{sec.title}</h3>
                  <div className="space-y-2 text-xs sm:text-sm text-muted-foreground font-light leading-relaxed">
                    {sec.paragraphs.map((p, pIdx) => (
                      <p key={pIdx}>{p}</p>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Right Column: Visual Trust Panel */}
          <div className="sticky top-28 bg-white border border-border p-6 sm:p-8 rounded-3xl space-y-6 shadow-sm relative overflow-hidden">
            <div className="absolute top-0 right-0 w-24 h-24 bg-primary/5 rounded-bl-[100px]" />
            
            <h3 className="text-sm font-extrabold uppercase tracking-wider text-primary flex items-center gap-2">
              <ShieldCheck className="h-4 w-4 text-[#DDA853]" />
              Verified Compliance
            </h3>
            
            <div className="space-y-4">
              <div className="p-4 bg-[#FAF8F5] rounded-xl space-y-2 border border-border/60">
                <span className="text-xs font-bold text-foreground block">AYUSH Regulatory Standards</span>
                <p className="text-[10px] text-muted-foreground leading-normal font-light">
                  Nirogi Tanman aligns all dietary plans and yoga exercises to safety limitations defined under traditional councils.
                </p>
              </div>

              <div className="p-4 bg-[#FAF8F5] rounded-xl space-y-2 border border-border/60">
                <span className="text-xs font-bold text-foreground block">HIPAA Privacy Protected</span>
                <p className="text-[10px] text-muted-foreground leading-normal font-light">
                  Your clinical consultation records and vital trends are encrypted under secure role-based controls.
                </p>
              </div>

              <div className="p-4 bg-[#FAF8F5] rounded-xl space-y-2 border border-border/60">
                <span className="text-xs font-bold text-foreground block">Practitioner Verification</span>
                <p className="text-[10px] text-muted-foreground leading-normal font-light">
                  All clinicians on the digital workspace are fully vetted before slot schedule activation.
                </p>
              </div>
            </div>

            <div className="pt-4 border-t border-border flex items-center gap-2.5 text-[10px] text-muted-foreground font-semibold uppercase tracking-wider">
              <Lock className="h-3.5 w-3.5 text-primary" />
              Secure Data Locker Enabled
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default PolicyDetailPage;
export { policiesData };
